# -*- coding: utf-8 -*-
"""data lens

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156pitxP4dCoRQx-XLPvxWNCTxr3m4t9t
"""

import pandas as pd

df = pd.read_csv("zomato.csv", encoding="latin-1")
print("Shape:", df.shape)
df.head()

df.isnull().sum()

df = df.drop(columns=["Unnamed: 0.1", "Unnamed: 0"])
df.head()

df["rate (out of 5)"] = pd.to_numeric(df["rate (out of 5)"], errors="coerce")
df["rate (out of 5)"] = df["rate (out of 5)"].fillna(df["rate (out of 5)"].median())

df["avg cost (two people)"] = pd.to_numeric(df["avg cost (two people)"], errors="coerce")
df["avg cost (two people)"] = df["avg cost (two people)"].fillna(df["avg cost (two people)"].median())

print(df.isnull().sum())

print("Duplicates:", df.duplicated().sum())
df = df.drop_duplicates()
print("New shape:", df.shape)

comparison = pd.DataFrame({
    "Metric": ["Total Rows", "Missing Values", "Columns"],
    "Before Cleaning": [7105, 125, 12],
    "After Cleaning": [df.shape[0], df.isnull().sum().sum(), df.shape[1]]
})
print(comparison)

import matplotlib.pyplot as plt

top_areas = df["area"].value_counts().head(10)
plt.figure(figsize=(10,5))
top_areas.plot(kind="bar", color="skyblue")
plt.title("Top 10 Areas by Number of Restaurants")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["rate (out of 5)"], bins=20, color="salmon", edgecolor="black")
plt.title("Distribution of Restaurant Ratings")
plt.tight_layout()
plt.show()

!pip install -q -U google-genai

from google.colab import userdata

api_key = userdata.get('GEMINI_API_KEY')
print("Length:", len(api_key))
print(repr(api_key))

import time
from google import genai

client = genai.Client(api_key=api_key)

for attempt in range(3):
    try:
        response = client.models.generate_content(
            model="gemini-3.8-flash",
            contents="Hello! Ek line me batao tum kya kar sakte ho."
        )
        print(response.text)
        break
    except Exception as e:
        print(f"Attempt {attempt+1} failed, retrying in 5 sec...")
        time.sleep(5)

import time

def ask_ai(prompt, retries=5, wait=10):
    for attempt in range(retries):
        try:
            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=prompt
            )
            return response.text
        except Exception as e:
            print(f"Attempt {attempt+1} failed ({type(e).__name__}), retrying in {wait} sec...")
            time.sleep(wait)
    return "AI abhi available nahi hai, thodi der baad try karo."

# Apne data ka summary
data_summary = df.describe().to_string()
columns_info = f"Columns: {list(df.columns)}"

prompt = f"""
Ye ek restaurant dataset ka summary hai:

{columns_info}

{data_summary}

Is data ke 3 important insights simple Hindi-English mix (Hinglish) me batao.
"""

result = ask_ai(prompt)
print(result)

# Jaan-bujhkar galat code (galat column name)
try:
    result = df["rating"].mean()   # "rating" naam ka column exist nahi karta
except Exception as e:
    error_message = str(e)
    print("Error aaya:", error_message)

    debug_prompt = f"""
    Mera pandas dataframe ke columns ye hain: {list(df.columns)}
    Maine ye code likha tha: df["rating"].mean()
    Mujhe ye error mila: {error_message}

    Simple Hinglish me batao galti kya hai aur sahi code kya hoga.
    """

    fix = ask_ai(debug_prompt)
    print("\nAI ka suggestion:\n", fix)

def ask_your_data(question):
    prompt = f"""
    Dataframe columns: {list(df.columns)}
    User ka sawal: {question}

    Simple Python pandas code likho jo ye sawal answer kare df dataframe par.
    Sirf code do, explanation mat do.
    """
    code = ask_ai(prompt)
    print("AI ne ye code suggest kiya:\n", code)

ask_your_data("Sabse zyada rating wala restaurant kaunsa hai?")

highest_rated_restaurant = df.loc[
    df["rate (out of 5)"].idxmax(), "restaurant name"
]
print("Sabse zyada rating wala restaurant:", highest_rated_restaurant)